[workspace]
members = [
    "rikctl",
    "scheduler",
    "riklet",
    "controller",
    "proto"
]

[workspace.dependencies]
prost = "0.11"
tonic = "0.8"
protobuf = { version = "3", features = ["with-bytes"] }
tonic-build = "0.8"
