name: RIK CI

on:
  push:
    branches:
      - main
      - patch/* # run CI on maintenance branches (ex patch/1.10)
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "docs/**"

  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - "**.md"
      - "**.txt"
      - "_license/**"
      - "docs/**"


jobs:
  lint:
    name: Validating code
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          # target: x86_64-unknown-linux-gnu
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        name: Init cache for cargo
      - uses: actions-rs/cargo@v1
        name: cargo clippy
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        name: cargo fmt check
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: check

  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: libc
        run: |
          sudo apt update 
          sudo apt install -y libc6 libssl-dev protobuf-compiler
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          # target: x86_64-unknown-linux-gnu
          override: true
      - uses: Swatinem/rust-cache@v2
      # Some tests must be running with root user, to do that we force tests to run with sudo
      - name: force cargo to use root user
        run: |
          mkdir .cargo || true
          echo "[target.x86_64-unknown-linux-gnu]" > .cargo/config
          echo "runner = 'sudo -E'" >> .cargo/config
      - uses: actions-rs/cargo@v1
        with:
          command: test

  build:
    name: Building code
    needs:
      - lint
      - tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: build

